name: Auto-merge on approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  automerge:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        uses: devops-infra/action-pull-request-merge@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}